### ISSUE TITLE
Memory Leak Issue (MYAudioTapProcessor.m)

### ISSUE THREAD

**Issue by emjoseph** [akhilcb/ACBAVPlayerExtension#3] opened 2020-04-09 18:33 UTC
I ran some profiling with Instruments and found that this snippet in `MYAudioTapProcessor.m`, in particular the malloc,  is causing severe memory leaks. I didn't need the channelVolumeList functionality for my use case so I commented it out but wanted to flag this for others.

```
if (aCount > 0) {
        context->channelVolumeList = malloc(aCount * sizeof(float));
        if (context->channelVolumeList == 0) {
            NSLog(@"Error! could not initialize channel volume list");
        }
}
```

**Comment by akhilcb** [comment] 2020-04-11 23:50
This is fixed in v2.1. I tried with sample project and I am not able to reproduce this leak with my fix.

**Closed as completed** 2020-04-14 22:59 UTC
Labels: bug, completed
